ALTER TABLE wb_user
    ADD COLUMN first_name TEXT NOT NULL DEFAULT 'N/A',
    ADD COLUMN middle_name TEXT NOT NULL DEFAULT 'N/A',
    ADD COLUMN last_name TEXT NOT NULL DEFAULT 'N/A',
    ADD COLUMN birthday DATE NOT NULL DEFAULT CURRENT_DATE,
    ADD COLUMN cell_phone TEXT NOT NULL DEFAULT 'N/A',
    ADD COLUMN gender TEXT NOT NULL DEFAULT 'MALE',
    ADD COLUMN user_type TEXT NOT NULL DEFAULT 'STUDENT',
    ADD COLUMN student_id INTEGER;
